{% set name = "django-parler" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51c33e7c0d3ca139d1f40ca4253894121a25d9df18076b8fafa573ab0d440010

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.7
    - six

test:
  commands:
    - python -c "from django.conf import settings; settings.configure(); import parler"

about:
  home: https://pypi.org/project/django-parler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple Django model translations without nasty hacks.

  description: |
    Features:
      - Nice admin integration
      - Access translated attributes like regular attributes.
      - Automatic fallback to the default language.
      - Separate table for translated fields, compatible with django-hvad.
      - Plays nice with others, compatible with django-polymorphic, django-mptt and such:
        - No ORM query hacks.
        - Easy to combine with custom Manager or QuerySet classes.
        - Easy to construct the translations model manually when needed.

  doc_url: https://django-parler.readthedocs.io/
  dev_url: https://github.com/edoburu/django-parler/

extra:
  recipe-maintainers:
    - kcemenike
